// <auto-generated />
namespace BangHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202303220933098_migration_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
